# Generated by Django 3.2.19 on 2023-12-03 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.CharField(max_length=255)),
                ('vote', models.IntegerField(blank=True, default=0, null=True)),
                ('co_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_leader', related_query_name='co_leader', to='api.leader')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leader')),
            ],
        ),
    ]
