# Generated by Django 3.2.19 on 2023-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='has_vote',
            field=models.BooleanField(default=False),
        ),
    ]
