# Generated by Django 3.2.19 on 2023-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userdata_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='co_leader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='leader',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Leader',
        ),
    ]
