# Generated by Django 3.2.19 on 2023-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20231215_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='static/dummy.jpg', null=True, upload_to='goods/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='static/dummy.jpg', null=True, upload_to='goods/product/'),
        ),
    ]
