# Generated by Django 3.2.19 on 2023-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20231215_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_img',
            field=models.ImageField(blank=True, default='dummy/dummy.jpg', null=True, upload_to='goods/category/'),
        ),
    ]
