# Generated by Django 3.2.19 on 2023-12-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_category_category_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='dummy/dummy.jpg', null=True, upload_to='goods/product/'),
        ),
    ]
